# Generated by Django 3.2.9 on 2021-11-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=40)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=40)),
                ('merchant', models.CharField(default='MERCHANTS', max_length=100)),
                ('date_processed', models.DateTimeField(auto_now_add=True)),
                ('approved_expenses', models.IntegerField(default='0')),
                ('total_amount', models.DecimalField(decimal_places=2, default='0', max_digits=40)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.CharField(max_length=10, null=True)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('deduction', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('staff_paid', models.IntegerField(null=True)),
                ('payroll_status', models.CharField(choices=[('Successful', 'Successful'), ('Pending', 'Pending')], default='Successful', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=40)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('work_email', models.CharField(max_length=100, null=True)),
                ('personal_email', models.CharField(max_length=100, null=True)),
                ('employee_id', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('date_processed', models.DateTimeField(auto_now_add=True, null=True)),
                ('employment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('insurance_number', models.CharField(max_length=100, null=True)),
                ('tax_pin_number', models.CharField(max_length=100, null=True)),
                ('paye', models.DecimalField(decimal_places=2, max_digits=40, null=True)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=40, null=True)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=40, null=True)),
                ('tax_deducted', models.DecimalField(decimal_places=2, max_digits=40, null=True)),
                ('pension', models.DecimalField(decimal_places=2, max_digits=40, null=True)),
                ('sacco', models.DecimalField(decimal_places=2, max_digits=40, null=True)),
                ('medical_cover', models.DecimalField(decimal_places=2, max_digits=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
    ]
