# Generated by Django 3.2.9 on 2021-11-18 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payroll_staff_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='company',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(default=datetime.datetime(2021, 11, 18, 19, 25, 36, 332160, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='employment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, null=True, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='insurance',
            field=models.DecimalField(null=True, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='insurance_number',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='medical_cover',
            field=models.DecimalField(decimal_places=2, null=True, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile_number',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, null=True, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='paye',
            field=models.DecimalField(decimal_places=2, null=True, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='pension',
            field=models.DecimalField(decimal_places=2, null=True, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='personal_email',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='sacco',
            field=models.DecimalField(decimal_places=2, null=True, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='tax_deducted',
            field=models.DecimalField(decimal_places=2, null=True, max_digits=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='tax_pin_number',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='work_email',
            field=models.CharField(null=True, max_length=100),
            preserve_default=False,
        ),
    ]
