# Generated by Django 3.2.9 on 2021-11-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20211125_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approve',
            name='company',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='date_processed',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='department',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='employment_date',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='gross_pay',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='insurance_number',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='location',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='medical_cover',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='net_pay',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='paye',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='pension',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='position',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='sacco',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='tax_deducted',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='tax_pin_number',
        ),
        migrations.RemoveField(
            model_name='approve',
            name='work_email',
        ),
        migrations.AddField(
            model_name='staff',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_processed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='employment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='insurance_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='medical_cover',
            field=models.DecimalField(decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='paye',
            field=models.DecimalField(decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='pension',
            field=models.DecimalField(decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='personal_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='sacco',
            field=models.DecimalField(decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='tax_deducted',
            field=models.DecimalField(decimal_places=2, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='tax_pin_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='work_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
