# Generated by Django 3.2.9 on 2021-11-18 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20211118_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_processed',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
    ]
