# Generated by Django 3.2.9 on 2021-11-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20211122_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='mobile_number',
        ),
    ]
