# Generated by Django 3.2.9 on 2021-11-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_staff_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='insurance',
        ),
    ]
