# Generated by Django 3.2.9 on 2021-11-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_staff_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='company',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_processed',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='employment_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='gross_pay',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='insurance_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='location',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='medical_cover',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='net_pay',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='paye',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='pension',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='sacco',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='tax_deducted',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='tax_pin_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='work_email',
        ),
    ]
