# Generated by Django 3.2.9 on 2021-11-15 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alter_user_national_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='work email')),
                ('personal_email', models.EmailField(max_length=254, unique=True, verbose_name='personal email')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE')),
                ('profile_pic', models.ImageField(null=True, upload_to='profile/')),
                ('insurance_number', models.CharField(max_length=20, null=True)),
                ('marital_status', models.BooleanField(null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('rather_not_say', 'rather_not_say')], max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
