# Generated by Django 3.2.9 on 2021-11-15 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_auto_20211115_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRelationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of relationship')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=20, null=True)),
                ('branch', models.CharField(max_length=20, null=True)),
                ('account_number', models.CharField(max_length=20, null=True)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_date', models.DateField(auto_now_add=True)),
                ('position', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(max_length=20, null=True)),
                ('employment_type', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('company_id', models.CharField(max_length=20, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name="Emergency contact's name")),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name="Emergency contact's phone number")),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.emergencyrelationships')),
            ],
        ),
    ]
