# Generated by Django 3.2.9 on 2021-11-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_emergencyinformation_emergencyrelationships_employmentinformation_paymentinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyinformation',
            options={'verbose_name': 'Emergency information', 'verbose_name_plural': 'Emergency informations'},
        ),
        migrations.AlterModelOptions(
            name='emergencyrelationships',
            options={'verbose_name': 'Emergency relationship', 'verbose_name_plural': 'Emergency relationships'},
        ),
        migrations.AlterModelOptions(
            name='employmentinformation',
            options={'verbose_name': 'Employment Information', 'verbose_name_plural': 'Employment Information'},
        ),
        migrations.AlterModelOptions(
            name='paymentinformation',
            options={'verbose_name': 'Payments Information', 'verbose_name_plural': 'Payment Information'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
