# Generated by Django 3.2.9 on 2021-11-24 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('surname', models.CharField(max_length=30)),
                ('other_names', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='work email')),
                ('national_id', models.CharField(max_length=8)),
                ('date_of_birth', models.DateField(null=True)),
                ('country', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyRelationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of relationship')),
            ],
            options={
                'verbose_name': 'Emergency relationship',
                'verbose_name_plural': 'Emergency relationships',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='The role of a user in the organisation')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30, null=True)),
                ('branch', models.CharField(max_length=30, null=True)),
                ('account_number', models.CharField(max_length=20, null=True)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_email', models.EmailField(max_length=254, null=True, verbose_name='personal email')),
                ('profile_pic', models.ImageField(null=True, upload_to='profile/')),
                ('marital_status', models.CharField(choices=[('married', 'married'), ('single', 'single'), ('divorced', 'divorced'), ('widow', 'widow')], max_length=50, null=True)),
                ('insurance_number', models.CharField(max_length=20, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name="Emergency contact's name")),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='KE', verbose_name="Emergency contact's phone number")),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_information', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.emergencyrelationships')),
            ],
            options={
                'verbose_name': 'Emergency information',
                'verbose_name_plural': 'Emergency informations',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_staff', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('headquarters', models.CharField(max_length=50, null=True)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('branches', models.IntegerField(null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='company_logo/')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='superadmin.companytypes')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superadmin.role'),
        ),
    ]
