# Generated by Django 3.2.9 on 2021-11-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_alter_employee_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Ethiopia', 'Ethiopia'), ('Egypt', 'Egypt'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Nigeria', 'Nigeria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Ethiopia', 'Ethiopia'), ('Egypt', 'Egypt'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Nigeria', 'Nigeria')], max_length=100),
        ),
    ]
