# Generated by Django 3.2.9 on 2021-11-20 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_type', to='human_resource.leavetype'),
        ),
    ]
