# Generated by Django 3.2.9 on 2021-11-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinformation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='superadmin.company'),
        ),
    ]
