# Generated by Django 3.2.9 on 2021-11-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('work_email', models.EmailField(max_length=50, null=True, unique=True)),
                ('personal_email', models.EmailField(max_length=50, null=True, unique=True)),
                ('id_number', models.CharField(max_length=50, null=True, unique=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('marital_status', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
