# Generated by Django 3.2.9 on 2021-11-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='soft_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employmentinformation',
            name='soft_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='soft_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='soft_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='offerletter',
            name='soft_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledinterview',
            name='soft_delete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
