# Generated by Django 3.2.9 on 2021-11-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinformation',
            name='employment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resource.employmenttype'),
        ),
    ]
