# Generated by Django 3.2.9 on 2021-11-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_auto_20211120_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledinterview',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.ManyToManyField(related_name='leave_type', to='human_resource.LeaveType'),
        ),
    ]
