# Generated by Django 3.2.9 on 2021-11-25 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alter_employee_employee_id'),
        ('human_resource', '0002_alter_employmentinformation_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinformation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='superadmin.company'),
        ),
    ]
