# Generated by Django 3.2.9 on 2021-11-25 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resource', '0002_employmentinformation_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.AddField(
            model_name='employmentinformation',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='soft_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employmentinformation',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employmentinformation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduledinterview',
            name='interview_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='scheduledinterview',
            name='interview_time_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledinterview',
            name='interview_time_to',
            field=models.TimeField(),
        ),
    ]
