# Generated by Django 3.2.9 on 2021-11-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_auto_20211117_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
