name: DeployToHerokuServer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    - name: Install dependencies
      run: /
        pipenv install
    - name: Run tests
      run: /
        python manage.py rest

    - name: Successful Message
      run: echo Successfully Deployed!!