name: DeployToHerokuServer

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Merge with development
      # - uses: actions/checkout@v2
      # - uses: everlytic/branch-merge@1.1.2
      #   with:
      #     github_token: ${{ github.token }}
      #     source_ref: ${{ github.ref }}
      #     target_branch: "main"
      #     commit_message_template: "[Automated] Merged {source_ref} into target {target_branch}"

      # - name: Deployment to heroku
      # - uses: actions/checkout@v2
      # - uses: akhileshns/heroku-deploy@v3.4.6
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "machachari"
      #     heroku_email: "ken.mbira@student.moringaschool.com"
      #     branch: "main"

      - name: Successful Message
        run: echo Successfully Deployed!!
