name: DeployToHerokuServer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: /
          python manage.py test

      - name: Successful Message
        run: echo Successfully Deployed!!
