name: test ci

on:
  workflow_call:
    secrets:
      SECRET_KEY:
        required: true
      EMAIL_USE_TLS: 
        required: true
      EMAIL_HOST: 
        required: true
      EMAIL_PORT: 
        required: true
      EMAIL_HOST_USER: 
        required: true
      EMAIL_HOST_PASSWORD: 
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        id: cacheStep
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Initiate virtual environment
        if: steps.cacheStep.outputs.cache-hit != 'true'
        run: |
          pip install pipenv
          pipenv install --system

      - name: test secrets
        run: |
          echo "hello ${{ env.SECRET_KEY }}"
          echo "hello ${{ env.SECRET_KEY }}"

      - name: Run Tests
        run: |
          python3.8 manage.py migrate
          python3.8 manage.py test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }} 