name: test ci

on:
  # push:
  #   # branches: [ft-superadmin]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Initiate virtual environment
        run: |
          pip install pipenv
          pipenv install --system

      - name: test secrets
        run: echo "hello ${{ env.SECRET_KEY }}"
      - name: Run Tests
        run: |
          python3.8 manage.py migrate
          python3.8 manage.py test
        with:
          SECRET_KEY: ${{SECRET_KEY }}
          EMAIL_USE_TLS: ${{EMAIL_USE_TLS }}
          EMAIL_HOST: ${{EMAIL_HOST }}
          EMAIL_PORT: ${{EMAIL_PORT }}
          EMAIL_HOST_USER: ${{EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{EMAIL_HOST_PASSWORD }}