name: test ci

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Initiate virtual environment
      run: |
          pip install pipenv
          pipenv install --system
          
    - name: Run Tests
      run: |
        python3.8 manage.py test
