name: test ci

on:
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Initiate virtual environment
        run: |
          pip install pipenv
          pipenv install --system

      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.KEY_KEY }}
          EMAIL_USE_TLS : True
          EMAIL_HOST : 'smtp.gmail.com'
          EMAIL_PORT : 587
          EMAIL_HOST_USER : 'ken.mbira@student.moringaschool.com'
          EMAIL_HOST_PASSWORD : '5startrek#'
        run: |
          python3.8 manage.py migrate
          python3.8 manage.py test
