name: Run tests

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt-get install libpq-dev -y
        pip install pipenv
    - name: Run Tests
      run: |
        python manage.py test
        
    - name: Successful Message
      run: echo Successfully Deployed!!
